# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jX87_2525g3k9JBndZ_gX4TNB_OhprnD
"""

import streamlit as st
import pickle
from sklearn.tree import export_graphviz

arquivo = open('arvore.pkl', 'rb')
arvore = pickle.load(arquivo)

individuo = []
st.text_input('Digite o sexo do paciente (masculino/feminino)', key='sexo')
if st.session_state.sexo.lower() == masculino:
  individuo.append(0)
else:
  individuo.append(1)

st.text_input('qual a idade?', key='fx')
idade = int(st.session_state.fx)
if 59<fx<70:
  individuo.append(0)
else:
  if 2<fx<5:
    individuo.append(1)
  else:
    if 49<fx<60:
      individuo.append(2)
    else:
      if 4<fx<10:
        individuo.append(3)
      else:
          if 29<fx<40:
            individuo.append(4)
          else:
              if 69<fx<80:
                individuo.append(5)
              else:
                  if 9<fx<15:
                    individuo.append(6)
                  else:
                      if fx<2:
                        individuo.append(7)
                      else:
                          if 19<fx<30:
                            individuo.append(8)
                          else:
                              if 14<fx<20:
                                individuo.append(9)
                              else:
                                  if 39<fx<40:
                                    individuo.append(10)
                                  else:
                                      individuo.append(11)

st.text_input = input("O indivíduo está hospitalizado? s/n", key='hospitalizado')
if st.session_state.hospitalizado.lower() == 's':
  individuo.append(0)
else:
  individuo.append(1)

st.text_input = input("O indivíduo tem febre? s/n", key='febre')
if st.session_state.febre.lower() == 's':
  individuo.append(0)
else:
  individuo.append(1)

st.text_input = input("O indivíduo tem tosse? s/n", key='tosse')
if st.session_state.febre.lower() == 'n':
  individuo.append(0)
else:
  individuo.append(1)

st.text_input = input("O indivíduo tem dor de garganta? s/n", key='garganta')
if st.session_state.garganta.lower() == 's':
  individuo.append(0)
else:
  individuo.append(1)

st.text_input = input("O indivíduo tem dispneia? s/n", key='dispneia')
if st.session_state.dispneia.lower() == 's':
  individuo.append(0)
else:
  if st.session_state.dispneia.lower() == 'nao info':
    individuo.append(1)
  else:
    if st.session_state.dispneia.lower() == 'n':
      individuo.append(2)

st.text_input = input("O indivíduo é gestante? s/n", key='gestante')
if st.session_state.gestante.lower() == 's':
  individuo.append(0)
else:
  individuo.append(1)

st.text_input = input("O indivíduo se identifica com qual raça/cor? s/n", key='cor')
if st.session_state.cor.lower() == 'nao info':
  individuo.append(0)
else:
  if st.session_state.cor.lower() == 'preta':
    individuo.append(1)
  else:
    if st.session_state.cor.lower() == 'parda':
      individuo.append(2)
    else:
      if st.session_state.cor.lower() == 'indigena':
        individuo.append(3)
      else:
          if st.session_state.cor.lower() == 'parda':
            individuo.append(4)
          else:
            if st.session_state.cor.lower() == 'branca':
              individuo.append(5)
            else:
              if st.session_state.cor.lower() == 'amarela':
                individuo.append(6)

st.text_input = input("O indivíduo desenvolveu SRAG? s/n", key='srag')
if st.session_state.srag.lower() == 's':
  individuo.append(0)
else:
  individuo.append(1)

